### ISSUE TITLE
Can't use in Internet Explorer 11

### ISSUE THREAD

**Issue by rszczypka** [WhichBrowser/Parser-JavaScript#17]
Is there a chance to make Parser-JavaScript ES5 ready?

**Comment by mariotsi** [comment]
Hi @rszczypka. This library is intended for beign used on a Node backend. However I'm thinking to a ES5 version in order to support older version of Node.

**Comment by mariotsi** [comment]
Hello, no ES5 version will be created since the support of ES6 is wide across Node. Closing
