### ISSUE TITLE
JS Build File / Distrubtion

### ISSUE THREAD

**Issue by KyleMit** [WhichBrowser/Parser-JavaScript#18]
ES6, NPM, and Yarn Dummy here.... trying to suss out how to add to a jsFiddle or Plunk or other webproject that doesn't have those build engines baked in.  Is there a simple JS build file that contains the output of the project.  Is it possible to build one a put it in a /dist folder?

**Comment by mariotsi** [comment]
Hi @KyleMit. I'll investigate the possibility to fulfill you request in the next month. I'm changing job just now and I haven't much spare time atm.

**Comment by koconder** [comment]
@KyleMit perhaps we can use TravisCI to build from releases, and nightly builds from branches or latest commits? - Not sure where you could host the JS though

**Comment by mariotsi** [comment]
Hosting is not an issue, there are CDN-like mirrors for npm packages as https://unpkg.com/ so the bundle could be created as part of the build step and released to NPN. 
I just have to find the time for set up the bundler and, in order to close #17, also Babel.

**Comment by mariotsi** [comment]
Closing. This is inactive from a while and won't be a priority
