### ISSUE TITLE
Microsoft Edge bug?, Television?

### ISSUE THREAD

**Issue by MaizeStarch** [WhichBrowser/Parser-JavaScript#19]
Hi! I'm using the plugin in an Ionic project, everything seems to be working fine.

Works on Android, iOS, browsers like Chrome, Firefox, Safari.

All good, except Microsoft Edge 16.

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299
```

It crashes when I instantiate the WhichBrowser object.

Debugging in Microsoft Edge debugger, Shows that it crashes in a line (if statement)

here's the internal file: Television.js

```
/* Generic model information */

  static detectGenericTelevisionModels(ua) {
    let match;
    if ((match = /\(([^,(]+),\s*([^,(]+),\s*(?:[Ww]ired|[Ww]ireless)\)/u.exec(ua))) {               //  <----- IT CRASHES HERE
      const vendorName = Manufacturers.identify(Constants.deviceType.TELEVISION, match[1]);
      const modelName = match[2].trim();
```

There it is, the if statement.

Is this bug? What am I doing wrong?

**Comment by mariotsi** [comment]
Hi!

First of all I wrote the library with Node in mind, so many Browsers will not work. You aren’t having any problem because you use all last or almost last versions.

No coming to the problem:
thanks for the detail report, can you add here a full stracktrace of the error please?

Thanks,
Simone

**Comment by MaizeStarch** [comment]
Oh I see, then I think I have to use the php backend, but my server doesn't support php neither node.

It's firebase, I will find the solution to my problem thanks for the answer.....

**Comment by mariotsi** [comment]
Hey, take a look at https://cloud.google.com/functions/ for running node functions and consume them from Firebase!

Let me know if you need further support for the issue.

**Comment by MaizeStarch** [comment]
Thanks for the help! I'll take a look at it.
