### ISSUE TITLE
Oculus Browser and Oculus Go are not detected correctly

### ISSUE THREAD

**Issue by frankolivier** [WhichBrowser/Parser-JavaScript#22]
headers: 'User-Agent: Mozilla/5.0 (Linux; Android 7.1.1; Pacific Build/N9F27L) AppleWebKit/537.36 (KHTML, like Gecko) OculusBrowser/4.0.0.17 SamsungBrowser/4.0 Chrome/61.0.3163.109 Mobile VR Safari/537.36'

The following should be returned:
    readable: 'Oculus Browser 4.0 on an Oculus Go running Android 7.1.1'

https://developer.oculus.com/documentation/vrweb/latest/concepts/carmel-getting-started/
https://www.oculus.com/go/

**Comment by mariotsi** [comment]
@NielsLeenheer 👆🏻
