### ISSUE TITLE
How to update devices?

### ISSUE THREAD

**Issue by etetlow** [WhichBrowser/Parser-JavaScript#42]
Hi. I'm trying to bring at least all of the android phones up to date and thought that is was a long winded but simple task of adding the new devices along with model codes to data/models-android.js. But it seems that this is not the case at all. I then read through some of the code to try and work what is going on and from my understanding , the model prefix has to be added to data/indices/models-androids.js, which I did, but the devices I've added are still not being recognised. So if you could help me it would be greatly appreciated and I promise to pass on the updates once I've finished.

Thanks.

**Comment by mariotsi** [comment]
Hi, please do not add models here. This project read the models data from https://github.com/WhichBrowser/Parser-PHP, so please open a PR against that project and we'll be able to review it and understand why is not working.
