### ISSUE TITLE
Incorrect browser engine detection

### ISSUE THREAD

**Issue by perqa** [WhichBrowser/Parser-JavaScript#70]
Samsung Tizen TVs sail under false flag; their user-agent string does not reflect actual browser engine, or engine version.

**Detected by WhichBrowser**
<img width="998" alt="Samsung_WB" src="https://user-images.githubusercontent.com/960796/218448397-af278e35-2046-4292-90f1-7d8fe5114945.jpg">

**Specified by [Samsung](https://developer.samsung.com/smarttv/develop/specifications/web-engine-specifications.html)**
<img width="804" alt="Samsung_actual" src="https://user-images.githubusercontent.com/960796/218446039-4e4c2147-52a4-4793-bac3-b4d35e662120.png">

**User-agent strings** 
```
        title        |                                                     user_agent                                                     
---------------------+--------------------------------------------------------------------------------------------------------------------
 Tizen 2017          | Mozilla/5.0 (SMART-TV; LINUX; Tizen 3.0) AppleWebKit/538.1 (KHTML, like Gecko) Version/3.0 TV Safari/538.1
 Tizen 2018 FHD      | Mozilla/5.0 (SMART-TV; LINUX; Tizen 4.0) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 TV Safari/537.36
 Tizen 2018 Standard | Mozilla/5.0 (SMART-TV; LINUX; Tizen 4.0) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 TV Safari/537.36
 Tizen 2019          | Mozilla/5.0 (SMART-TV; LINUX; Tizen 5.0) AppleWebKit/537.36 (KHTML, like Gecko) Version/5.0 TV Safari/537.36
 Tizen 2020 Standard | Mozilla/5.0 (SMART-TV; LINUX; Tizen 5.5) AppleWebKit/537.36 (KHTML, like Gecko) 69.0.3497.106/5.5 TV Safari/537.36
 Tizen 2020 Premium  | Mozilla/5.0 (SMART-TV; LINUX; Tizen 5.5) AppleWebKit/537.36 (KHTML, like Gecko) 69.0.3497.106/5.5 TV Safari/537.36
 Tizen 2021 Premium  | Mozilla/5.0 (SMART-TV; LINUX; Tizen 6.0) AppleWebKit/537.36 (KHTML, like Gecko) 76.0.3809.146/6.0 TV Safari/537.36
 Tizen 2021 Standard | Mozilla/5.0 (SMART-TV; LINUX; Tizen 6.0) AppleWebKit/537.36 (KHTML, like Gecko) 76.0.3809.146/6.0 TV Safari/537.36
 Tizen 2022          | Mozilla/5.0 (SMART-TV; LINUX; Tizen 6.5) AppleWebKit/537.36 (KHTML, like Gecko) 85.0.4183.93/6.5 TV Safari/537.36
```

I believe it would still be possible to correctly map browser engines by generating a fingerprint from their Modernizr profile, and compare to a fingerprint database generated from different browser engines and versions. I'm not sure, but it might be out of scope for this project?

**Comment by mariotsi** [comment]
Hello,
I don't believe using Mordernizr is the way forward. This project is an alternative to it, a discouraged one, if you have read the Readme :)
